apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      template: 
        spec:
          containers:
          - name: hello-cron
            image: vamsijakkula/hello-cron:latest
            command: ['sh', '-c','sleep 75']
          restartPolicy: OnFailure
  concurrencyPolicy: Replace
