apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      template: 
        spec:
          containers:
          - name: hello-cron
            image: vamsijakkula/hello-cron:latest
          restartPolicy: OnFailure
      parallelism: 2
      completions: 4
  concurrencyPolicy: Forbid
